python_sources = files(
  '__init__.py',
  'test_collection.py',
  'test_controller_indices.py',
  'test_events.py',
  'test_formatting.py',
  'test_functional.py',
  'test_host_config.py',
  'test_host_plugins.py',
  'test_le.py',
  'test_lifecycle.py',
  'test_logging.py',
  'test_mainloop.py',
  'test_proxy.py',
  'test_progress.py',
  'test_rpc.py',
  'test_utils.py',
  'test_vm.py',
  'test_xdist.py',
)

py.install_sources(
  python_sources,
  subdir: 'pytest_bluezenv/tests'
)
